Ruby on Rails Capstone Project
SnakyMz/Expense-app pull request #5
Opened 2023-11-23 09:33 UTC by SnakyMz

Things I have done:

- [ ] Installed Rails app
- [ ] Added Splash screen
- [ ] Implemented Devise for authentication and authorization
- [ ] Added Categories pages
- [ ] Added Transaction pages
- [ ] Added User details page
- [ ] Added tests for the app
- [ ] Deployed the app on render

2023-11-23 12:11 UTC, AmaduKamara requested changes
# Status: APPROVED 🟢 🟢 🟢

Hi @SnakyMz, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ You set up Gitflow correctly 👍🏽
✅ The Linter checks passed successfully 👍🏽
✅ Registration and Login features work fine as expected 👍🏽
✅ All features work fine 👍🏽
✅ Implemented tests and the tests passed successfully 👍🏽

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly show a piece of code in your presentation that you are proud of implementing.
- [ ] It would be nice if you could improve on the spacing of elements in your design. 

- [ ] Please add a little padding on the input fields for all form inputs and also it would be nice to add the width of the buttons to spread across just as the input fields. Kindly work on the other buttons as well.

<img width="434" alt="Screenshot 2023-11-23 at 11 44 42 AM" src="https://github.com/SnakyMz/Expense-app/assets/50941074/45c3a38e-1c52-4a9d-b1f5-c37a15ac72b4">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-11-23 12:11 UTC, AmaduKamara commented on README.md
> +
- [ ] You've done great work @SnakyMz, a good presentation done but you are missing out on a highlight of a piece of code you're proud of implementing. It would be nice if you could show the code section you implemented that you feel proud of so viewers could see the code while you talk briefly about its implementation. Kindly redo the video and show that part in your presentation. 👍🏽

2023-11-23 20:13 UTC, SnakyMz commented on README.md
> +
Thank you for the review
## I have made changes as suggested
![Screenshot 2023-11-24 014018](https://github.com/SnakyMz/Expense-app/assets/115364362/2050d549-1601-4bfd-9a46-dae926134f3c)

2023-11-23 20:46 UTC, Felix45 approved these changes
# Approved :green_circle:  🎉  🎉  🎉  🎉  🎉  🎉  🎉  🎉 
Hi @SnakyMz, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Application functions as expected :white_check_mark: 
- [x] Application is deployed online and works correctly :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:    
- [x] Implemented all the changes from the previous reviewer :white_check_mark:  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-23 21:21 UTC, merged

2023-11-24 08:04 UTC, AmaduKamara commented on README.md
> +
Good job working on the changes. 👍🏽

I am so sorry I made a mistake on the review status with Approve feedback instead of Required Changes.